for version in old new; do
cat ../cleaned/${version}_perturbations_cleaned.txt | awk '$2 == "KO" || $2 == "KD"' | cut -f4- | awk 'BEGIN {FS = "\t"} {gsub(";", "\t", $1); print $2 "\t" $1}' | awk 'BEGIN {FS = "\t"} {for(i = 2; i <= NF; i++){print $i "\t" $1}}' | sed 's/&/\t/g' | awk 'BEGIN {FS = "\t"} {for(i=2; i<=NF; i++){print $1 "\t" $i}}' | sort -u | cut -d';' -f1 | sort -k1,1 | awk 'BEGIN {FS = "\t"; cur = ""; names = ""} {if(cur != "" && cur != $1){print cur "\t" names; names = ""} cur = $1; names = names ";" $2} END {print cur "\t" names}' | sed 's/\t;/\t/g' > ${version}_gene_targets_wide.txt
(cat ${version}_gene_targets_wide.txt | grep -v ';' | cut -f1 | sort -u | join -t$'\t' -1 1 -2 2 - <(cat ../../import/sample_info.txt | cut -f-2 | sort -k2,2) | sort -k2,2 | join -t$'\t' -1 2 -2 1 - <(cat ../cleaned/${version}_perturbations_cleaned.txt | awk '$2 == "KO" || $2 == "KD"' | cut -f4 | sed 's/;/\n/g' | sort -u | grep -vwf - <(cat ../../import/sample_info.txt | cut -f-2) | sort -k1,1); cat ${version}_gene_targets_wide.txt | grep ';' | sort -k1,1 | join -t$'\t' -1 2 -2 1 <(cat ../../import/sample_info.txt | cut -f-2 | sort -k2,2) - | sort -k2,2 | join -t$'\t' -1 2 -2 2 - <(cat ${version}_gene_targets_wide.txt | sort -k1,1 | join -t$'\t' -1 2 -2 1 <(cat ../../import/sample_info.txt | cut -f-2 | sort -k2,2) - | sort -k2,2) | awk 'BEGIN {FS = "\t"} {print $1 "_" $2 "_" $4 "\t" $3 "\t" $5}' | sort -u | awk 'BEGIN {FS = "\t"} $2 != $3 {x = $3; gsub(";", "\t", x); print $1 "\t" $2 "\t" $3 "\t;" $2 ";\t" x}' | awk 'BEGIN {FS = "\t"} {for(i=5; i <= NF; i++){if(index($4, ";" $i ";") == 0){next} else{gsub(";" $i ";", ";", $4)}} if($4 != ";" && index(substr($4, 2, length($4) - 2), ";") == 0){print $1}}' | sed 's/_/\t/g') | sort -u | sort -k3,3 | join -t$'\t' -1 3 -2 1 - <(cat ../../import/sample_library_strategy.txt | awk '$2 == "RNA-Seq"' | cut -f1 | sort -u) | sort -k3,3 | join -t$'\t' -1 3 -2 1 - <(cat ../../import/sample_library_strategy.txt | awk '$2 == "RNA-Seq"' | cut -f1 | sort -u) | awk '{print $3 "\t" $1 "\t" $2}' > ${version}_gene_minusone_pairs.txt
cat ../cleaned/${version}_perturbations_cleaned.txt | awk '$2 == "KO" || $2 == "KD"' | cut -f1,3,4 | awk 'BEGIN {FS = "\t"} {gsub(";", "\t", $3); print $1 "\t" $2 "\t" $3}' | awk 'BEGIN {FS = "\t"} {gsub(";", "\t", $2); for(i=3; i <= NF; i++) {print $1 "\t" $i "\t" $2}}' | awk 'BEGIN {FS = "\t"} {for(i=3; i <= NF; i++){print $1 "\t" $2 "\t" $i}}' > ${version}_gene_control_perturb_pairs.txt
cat ../cleaned/${version}_perturbations_cleaned.txt | awk '$2 == "D"' | cut -f4- | awk 'BEGIN {FS = "\t"} {gsub(";", "\t", $1); print $2 "\t" $1}' | awk 'BEGIN {FS = "\t"} {for(i = 2; i <= NF; i++){print $i "\t" $1}}' | sed 's/&/\t/g' | awk 'BEGIN {FS = "\t"} {for(i=2; i<=NF; i++){print $1 "\t" $i}}' | sort -u | cut -d';' -f1 | sort -k1,1 | awk 'BEGIN {FS = "\t"; cur = ""; names = ""} {if(cur != "" && cur != $1){print cur "\t" names; names = ""} cur = $1; names = names ";" $2} END {print cur "\t" names}' | sed 's/\t;/\t/g' > ${version}_drug_targets_wide.txt
(cat ${version}_drug_targets_wide.txt | grep -v ';' | cut -f1 | sort -u | join -t$'\t' -1 1 -2 2 - <(cat ../../import/sample_info.txt | cut -f-2 | sort -k2,2) | sort -k2,2 | join -t$'\t' -1 2 -2 1 - <(cat ../cleaned/${version}_perturbations_cleaned.txt | awk '$2 == "D"' | cut -f4 | sed 's/;/\n/g' | sort -u | grep -vwf - <(cat ../../import/sample_info.txt | cut -f-2) | sort -k1,1); cat ${version}_drug_targets_wide.txt | grep ';' | sort -k1,1 | join -t$'\t' -1 2 -2 1 <(cat ../../import/sample_info.txt | cut -f-2 | sort -k2,2) - | sort -k2,2 | join -t$'\t' -1 2 -2 2 - <(cat ${version}_drug_targets_wide.txt | sort -k1,1 | join -t$'\t' -1 2 -2 1 <(cat ../../import/sample_info.txt | cut -f-2 | sort -k2,2) - | sort -k2,2) | awk 'BEGIN {FS = "\t"} {print $1 "_" $2 "_" $4 "\t" $3 "\t" $5}' | sort -u | awk 'BEGIN {FS = "\t"} $2 != $3 {x = $3; gsub(";", "\t", x); print $1 "\t" $2 "\t" $3 "\t;" $2 ";\t" x}' | awk 'BEGIN {FS = "\t"} {for(i=5; i <= NF; i++){if(index($4, ";" $i ";") == 0){next} else{gsub(";" $i ";", ";", $4)}} if($4 != ";" && index(substr($4, 2, length($4) - 2), ";") == 0){print $1}}' | sed 's/_/\t/g') | sort -u | sort -k3,3 | join -t$'\t' -1 3 -2 1 - <(cat ../../import/sample_library_strategy.txt | awk '$2 == "RNA-Seq"' | cut -f1 | sort -u) | sort -k3,3 | join -t$'\t' -1 3 -2 1 - <(cat ../../import/sample_library_strategy.txt | awk '$2 == "RNA-Seq"' | cut -f1 | sort -u) | awk '{print $3 "\t" $1 "\t" $2}' > ${version}_drug_minusone_pairs.txt
cat ../cleaned/${version}_perturbations_cleaned.txt | awk '$2 == "D"' | cut -f1,3,4 | awk 'BEGIN {FS = "\t"} {gsub(";", "\t", $3); print $1 "\t" $2 "\t" $3}' | awk 'BEGIN {FS = "\t"} {gsub(";", "\t", $2); for(i=3; i <= NF; i++) {print $1 "\t" $i "\t" $2}}' | awk 'BEGIN {FS = "\t"} {for(i=3; i <= NF; i++){print $1 "\t" $2 "\t" $i}}' > ${version}_drug_control_perturb_pairs.txt
for pert in gene drug; do
cat ${version}_${pert}_minusone_pairs.txt | awk '{print $1 "_" $2 "_" $3 "\t0"}' | sort -k1,1 | join -t$'\t' -a 1 -a 2 -o auto -e 0 - <(cat ${version}_${pert}_control_perturb_pairs.txt | awk '{print $1 "_" $2 "_" $3 "\t1"}' | sort -k1,1) | cut -f1,3 | sort -u > ${version}_${pert}_control_labels.txt
done
done

for pert in gene drug; do
cat new_${pert}_control_labels.txt  | awk 'BEGIN {FS = "_"} {print $1 "\t" $0}' | sort -k1,1 | join -t$'\t' - <(cat ../SNACKKSS_2C.txt | awk '$2 == "Ben"' | cut -f1 | sort -u) | cut -f2- | sort -u > independent_${pert}_control_labels.txt
done

(echo $'Perturbation type\tAgreed\tTrials\tObserved agreement\tExpected agreement\tKappa'
for pert in gene drug; do
cat old_${pert}_control_labels.txt | sort -u | sort -k1,1 | join -t$'\t' - <(cat independent_${pert}_control_labels.txt | cut -f1 | sort -u | cut -d_ -f2 | sort | uniq -c | awk '{print $2 "\t" 1 / $1}' | sort -k1,1 | join -t$'\t' <(cat independent_${pert}_control_labels.txt | awk 'BEGIN {FS = "_"}{print $2 "\t" $0}' | sort -k1,1) - | cut -f2- | sort -u | sort -k1,1) | cut -f2- | awk 'BEGIN {FS = "\t"; p1 = 0; p2 = 0; n1 = 0; n2 = 0; agreed = 0; disagreed = 0} {if($1 == 1){p1 += $3} else{n1 += $3} if($2 == 1){p2 += $3} else{n2 += $3} if($1 == $2){agreed += $3} else{disagreed += $3}} END {rate1 = p1/(p1+n1); rate2=p2/(p2+n2); pe = (rate1 * rate2) + ((1-rate1) * (1-rate2)); po = agreed / (agreed + disagreed); k = (po - pe) / (1 - pe); print "'$pert'\t" agreed "\t" (agreed + disagreed) "\t" po "\t" pe "\t" k}'
done) > agreement_stats.txt

(echo $'Perturbation type\tAgreed\tTrials\tObserved agreement\tExpected agreement\tKappa'
for pert in gene drug; do
cat old_${pert}_control_labels.txt | sort -u | sort -k1,1 | join -t$'\t' - <(cat independent_${pert}_control_labels.txt | cut -f1 | sort -u | cut -d_ -f2 | sort | uniq -c | awk '{print $2 "\t" 1 / $1}' | sort -k1,1 | join -t$'\t' <(cat independent_${pert}_control_labels.txt | awk 'BEGIN {FS = "_"}{print $2 "\t" $0}' | sort -k1,1) - | cut -f2- | sort -u | sort -k1,1) | cut -f2- | awk 'BEGIN {FS = "\t"; p1 = 0; p2 = 0; n1 = 0; n2 = 0; agreed = 0; disagreed = 0} {if($1 == 1){p1++} else{n1++} if($2 == 1){p2++} else{n2++} if($1 == $2){agreed++} else{disagreed++}} END {rate1 = p1/(p1+n1); rate2=p2/(p2+n2); pe = (rate1 * rate2) + ((1-rate1) * (1-rate2)); po = agreed / (agreed + disagreed); k = (po - pe) / (1 - pe); print "'$pert'\t" agreed "\t" (agreed + disagreed) "\t" po "\t" pe "\t" k}'
done) > agreement_stats_unweighted.txt

